name: CI Pipeline
on: [push]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bash ./runTests.sh
    cypress-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm install
                  npm run startBackend
                  npx cypress run --spec "cypress/integration/api/**"
            - uses: actions/download-artifact@v3
