name: CI Pipeline
on: [push]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: bash ./runTests.sh
    tests-cypress:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npx cypress run --spec "cypress/integration/api/**"
